[package]
name = "phd2_exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
derive = "1.0.0"
features = "0.10.0"
futures = "0.3.28"
pin-project = "1.1.0"
prometheus_exporter = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["full"] }
tokio-serde = "0.8.0"
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.8", features = ["codec"] }
